# Usa a imagem base do Python
FROM python:3.11

# Define o diretório de trabalho no container
WORKDIR /app

# Copia os arquivos para dentro do container
COPY requirements.txt .

# Instala as dependências do app
RUN pip install --no-cache-dir -r requirements.txt

# Copia tudo que esta na pasta atual do host para a pasta do conteuner
# Depois do RUN
COPY . .

# Expõe a porta que o Flask usa
EXPOSE 5000

# Comando padrão ao iniciar o container
CMD ["python", "app.py"]
